version: 0.2
phases:
  install:
    commands:
      - n 14.18.3
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - rm -rf node_modules
      - npm install
      - npm run start
  build:
    commands:
      #build
      - echo Building...
      - npm --prefix ./Frontend/ run build
artifacts:
  files:
    "**/*"
  discard-paths: no
  base-directory: client/build
