service: gigatester-backend

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'development'}
  region: us-east-1 #change based on where to deploy
  memorySize: 2048 # In MB, Max is 10240 MB.
  timeout: 60 # Note: API Gateway current maximum is 30 seconds
  logRetentionInDays: 30 # Set the default RetentionInDays for a CloudWatch LogGroup
  lambdaHashingVersion: 20201221
  environment:
    DB_ENV: ${env:NODE_ENV, self:provider.stage}
    logLevel: ${self:custom.loglevel.${self:provider.stage}}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'apigateway:*'
      Resource:
        - 'arn:aws:apigateway:${self:provider.region}::/restapis*'

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-aws-documentation
  - serverless-stack-output

package:
  include:
    - src/**/!(*.spec).js

functions:
  feedback:
    handler: src/functions/feedback/api/db/index.handler
    events:
      - http:
          path: feedback
          method: ANY
  feedbackMedia:
    handler: src/functions/feedback/api/media/index.handler
    events:
      - http:
          path: feedbackMedia
          method: ANY
  app:
    handler: src/app.handler
    events:
      - http: ANY /
      - http: 'ANY /{proxy+}'

custom:
  output:
    file: .serverless/output.json
  loglevel:
    development: 'info' # error/warn/info/debug
    qa: 'info' # error/warn/info/debug
    production: 'info' # error/warn/info/debug

# https://serverless.readme.io/docs/best-practices
# https://serverless-stack.com/chapters/organizing-serverless-projects.html
